name: Generate iiif manifests
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  schedule:
    - cron:  '2 1 * * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: node run
        run: node index.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: miniatures-iiif.fitzmuseum.cam.ac.uk
